docs: adiciona a documentação de como usar o modulo
mentoriaiac/iac-modulo-github pull request #4
Opened 2021-10-10 16:13 UTC by jandson-oliveira

# adiciona a documentação de como usar o modulo
Revisores: @Rehzende @snifbr @karollynecosta

- [x] Garanta que seu **topic/feature/bugfix branch** tenha uma branch nomeada e não a sua branch main esteja no PR
- [x] Dê um titulo que expresse o objetivo do PR
- [ ] Associe seu PR a uma Issue criada no repositósito. Caso seja uma correção de linguagem ou pequenas correções, não é necessário
- [x] Descreva o objetivo do PR
- [ ] Inclua links relevantes para a sua modificação/sugestão/correção
- [ ] Descreva um passo-a-passo para testar o seu PR

## Objetivo
criar uma documentação de como usar o modulo.

## Como testar
N/A

2021-10-30 02:30 UTC, gomex requested changes

2021-10-30 02:30 UTC, gomex commented on how-to-use-this-module/README.md
> +terraform init
Precisamos que aqui seja usado o make ao invés do terraform puro.

2021-10-30 02:30 UTC, gomex commented on how-to-use-this-module/README.md
> +terraform plan
Precisamos que aqui seja usado o make ao invés do terraform puro.

2021-10-30 02:30 UTC, gomex commented on how-to-use-this-module/README.md
> +terraform apply
Precisamos que aqui seja usado o make ao invés do terraform puro.

2021-10-31 20:01 UTC, snifbr approved these changes
@jandson-oliveira já fez a correção para usar comandos via make.

LGTM

2021-10-31 20:03 UTC, merged